twig:
    default_path: "%kernel.project_dir%/templates"
    # form_themes: ["bootstrap_5_layout.html.twig"]
    globals:
        facilityName: "%env(FACILITY_NAME)%"
        hostname: "%env(HOSTNAME)%"
        # base_path: '/docauposte'
    cache: "%kernel.cache_dir%/twig"
    optimizations: -1
when@test:
    twig:
        strict_variables: true
